# Generated by Django 5.0.6 on 2024-05-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL категории', max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL категории', max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Описание', null=True)),
                ('image', models.ImageField(blank=True, help_text='Изображение', null=True, upload_to='goods_images')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена', max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Скидка', max_digits=4)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Количество')),
                ('category', models.ForeignKey(help_text='Категория', on_delete=django.db.models.deletion.CASCADE, to='goods.categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ('category',),
            },
        ),
    ]
